#!/usr/bin/env bash
# Generated by Chock. Best-effort guard against destructive commands.
# Not a security boundary; bypasses are possible via aliases, quoting, or non-standard paths.
set -eu

is_dangerous_target() {
    local t="$1"
    # The tilde MUST be quoted on the pattern side. Unquoted `~/*` inside [[ ]] undergoes
    # tilde expansion, so the pattern became the caller's own home path and could never
    # match the literal "~/..." an agent actually types -- `rm -rf ~/anything` was allowed
    # for as long as this guard has existed, while `rm -rf ~` was caught.
    #
    # `$HOME/...` is checked literally for a different reason: the guard inspects the
    # command BEFORE a shell expands it, so it sees the variable, not the path it becomes.
    # At execution time it expands to an absolute path and deletes exactly what `/*` was
    # meant to stop.
    [[ "$t" == "/" || "$t" == "~" || "$t" == "." || "$t" == ".."         || "$t" == /* || "$t" == "~"/*         || "$t" == '$HOME' || "$t" == '${HOME}'         || "$t" == '$HOME'/* || "$t" == '${HOME}'/* ]]
}

# Options that consume the NEXT token as their VALUE, for the wrappers and CLIs this guard
# parses. Their values must be dropped before positions are resolved, or a value that looks
# like a program or a verb -- `sudo -u postgres dropdb`, `helm --kube-context prod uninstall`
# -- shifts cmd_word and the action slot and slips past. Best-effort: an unusual value-flag
# not listed here can still shift a slot; that residual is named in the manifest bypasses.
_is_value_flag() {
    case "$1" in
        --namespace | --kube-context | --kubeconfig | --context | --region | --profile | --project | --account | --output | --format | --host | --config | --endpoint-url | --cluster | --user | --server | --kube-apiserver | --log-level | --configuration | --chdir)
            return 0
            ;;
        -u | -g | -p | -H | -o | -n | -c | -C)
            return 0
            ;;
        *) return 1 ;;
    esac
}

# Flatten arguments for membership checks.
all_args=("$@")
flags=()
targets=()
positionals=()
subcommand=""
skip_next=0

for arg in "$@"; do
    if [[ "$skip_next" -eq 1 ]]; then
        # This token is the value of the preceding value-flag; it is neither a flag nor a
        # positional operand, so it must not land in `positionals`/`targets`.
        skip_next=0
        continue
    fi
    if [[ "$arg" =~ ^- ]]; then
        if _is_value_flag "$arg"; then
            skip_next=1
        fi
        if [[ "$arg" =~ ^-- ]]; then
            flags+=("$arg")
        else
            # Expand combined short flags, e.g. -rf -> -r -f.
            for ((i=1; i<${#arg}; i++)); do
                flags+=("-${arg:i:1}")
            done
        fi
    else
        # Every non-flag token, in order. Family checks below read the destructive verb
        # from the SLOT the tool parses it in, so a bucket/path/object NAMED like a verb
        # ("aws s3 cp ... rm", "docker volume inspect rm", "helm list delete") is not
        # mistaken for the verb.
        positionals+=("$arg")
        case "$arg" in
            git | rm | kubectl | terraform | aws | helm | docker | gcloud | dropdb) ;;
            push | reset | clean | delete | destroy | checkout)
                if [[ -z "$subcommand" ]]; then subcommand="$arg"; fi
                ;;
            *) targets+=("$arg") ;;
        esac
    fi
done

# The positional token N slots after the first occurrence of $1 (empty if absent).
pos_after() {
    local want="$1" off="$2" i
    for i in "${!positionals[@]}"; do
        if [[ "${positionals[i]}" == "$want" ]]; then
            printf '%s' "${positionals[i + off]:-}"
            return 0
        fi
    done
    return 1
}

# The program actually invoked: the first positional that is not a transparent wrapper.
cmd_word=""
for _p in "${positionals[@]}"; do
    case "$_p" in
        sudo | env | command | exec | nice | nohup | time | doas) continue ;;
        *)
            cmd_word="$_p"
            break
            ;;
    esac
done

has_flag() {
    local needle="$1"
    for f in "${flags[@]}"; do
        [[ "$f" == "$needle" ]] && return 0
    done
    return 1
}

# git accepts any unambiguous prefix of a long option, so `git reset --h` == `--hard`.
# Matches a flag token that is a prefix of $1 and at least $2 characters long (the
# unambiguous floor). Deliberately NOT used for `push --force`: there `--force` is itself
# a prefix of the SAFE `--force-with-lease`, and git rejects shorter abbreviations as
# ambiguous, so exact matching is correct and prefix-matching would block the safe form.
has_flag_prefix() {
    local full="$1" min="$2" f
    for f in "${flags[@]}"; do
        [[ ${#f} -ge $min && "$full" == "$f"* ]] && return 0
    done
    return 1
}

has_command() {
    local cmd="$1"
    for a in "${all_args[@]}"; do
        [[ "$a" == "$cmd" ]] && return 0
    done
    return 1
}

# rm -rf /, rm -fr /var, rm -r -f /, etc.
if has_command "rm"; then
    if has_flag "-r" || has_flag "--recursive"; then
        if has_flag "-f" || has_flag "--force"; then
            for t in "${targets[@]}"; do
                if is_dangerous_target "$t"; then
                    echo "BLOCKED: destructive rm command targeting '$t' is not allowed without approval." >&2
                    exit 1
                fi
            done
        fi
    fi
fi

# git subcommands
if has_command "git"; then
    if [[ "$subcommand" == "push" ]]; then
        if has_flag "-f" || has_flag "--force"; then
            echo "BLOCKED: git push --force is not allowed; use --force-with-lease on a feature branch." >&2
            exit 1
        fi
        # A leading '+' on a refspec force-updates the remote ref with no --force flag:
        # `git push origin +main` and `git push origin +refs/heads/main` both overwrite.
        for t in "${targets[@]}"; do
            if [[ "$t" == +* || "$t" == *:+* ]]; then
                echo "BLOCKED: git push with a '+' force-refspec ('$t') overwrites the remote ref; use --force-with-lease on a feature branch." >&2
                exit 1
            fi
        done
    elif [[ "$subcommand" == "reset" ]]; then
        if has_flag_prefix "--hard" 3; then
            echo "BLOCKED: git reset --hard is not allowed without approval." >&2
            exit 1
        fi
    elif [[ "$subcommand" == "clean" ]]; then
        if has_flag "-f" || has_flag_prefix "--force" 3; then
            echo "BLOCKED: git clean -f is not allowed without approval." >&2
            exit 1
        fi
    elif [[ "$subcommand" == "checkout" ]]; then
        for t in "${targets[@]}"; do
            if [[ "$t" == "." ]]; then
                echo "BLOCKED: git checkout . is not allowed without approval." >&2
                exit 1
            fi
        done
    fi
fi

# kubectl delete
if has_command "kubectl" && [[ "$subcommand" == "delete" ]]; then
    echo "BLOCKED: kubectl delete is not allowed without approval." >&2
    exit 1
fi

# terraform destroy
if has_command "terraform" && [[ "$subcommand" == "destroy" ]]; then
    echo "BLOCKED: terraform destroy is not allowed without approval." >&2
    exit 1
fi

# aws s3 rm --recursive; aws s3 rb --force. The action is read from the slot AFTER `s3`,
# so `aws s3 cp --recursive <src> rm` (a destination dir named rm) stays allowed. A
# single-object `aws s3 rm` stays allowed too -- blocking it would make routine cleanup
# unsatisfiable.
if has_command "aws" && has_command "s3"; then
    aws_action="$(pos_after s3 1)"
    if [[ "$aws_action" == "rm" ]] && has_flag "--recursive"; then
        echo "BLOCKED: aws s3 rm --recursive is not allowed without approval." >&2
        exit 1
    fi
    if [[ "$aws_action" == "rb" ]] && has_flag "--force"; then
        echo "BLOCKED: aws s3 rb --force is not allowed without approval." >&2
        exit 1
    fi
fi

# dropdb: the command's only job is deleting a database. Blocked only when it is the
# PROGRAM invoked, not when a path or db name merely contains "dropdb".
if [[ "$cmd_word" == "dropdb" ]]; then
    echo "BLOCKED: dropdb is not allowed without approval." >&2
    exit 1
fi

# helm uninstall (and its v2 alias `helm delete`) removes every resource in the release.
# The action is the slot after `helm`, so `helm list delete` (a release named delete) stays
# allowed.
if has_command "helm"; then
    helm_action="$(pos_after helm 1)"
    if [[ "$helm_action" == "uninstall" || "$helm_action" == "delete" ]]; then
        echo "BLOCKED: helm uninstall/delete is not allowed without approval." >&2
        exit 1
    fi
fi

# docker: volume rm / volume prune destroy data; system prune sweeps broadly. The action is
# the slot after the object, so `docker volume inspect rm` and `docker volume ls prune`
# (a volume named rm/prune) stay allowed.
if has_command "docker"; then
    if has_command "volume"; then
        docker_vol_action="$(pos_after volume 1)"
        if [[ "$docker_vol_action" == "rm" || "$docker_vol_action" == "prune" ]]; then
            echo "BLOCKED: docker volume rm/prune is not allowed without approval." >&2
            exit 1
        fi
    fi
    if has_command "system" && [[ "$(pos_after system 1)" == "prune" ]]; then
        echo "BLOCKED: docker system prune is not allowed without approval." >&2
        exit 1
    fi
fi

# gcloud … delete, across services. `--filter=delete` is a flag, not the word, and does
# not trip this.
if has_command "gcloud" && has_command "delete"; then
    echo "BLOCKED: gcloud delete is not allowed without approval." >&2
    exit 1
fi

# PowerShell / cmd destructive removals. POSIX shlex (the adapter's tokenizer) mangles
# Windows paths (C:\x -> C:x) and PowerShell long flags (-Recurse -> -R -e -c ...), so this
# matches the RAW command text (CHOCK_RAW_COMMAND, set by the adapter and the eval harness)
# rather than argv. A recursive removal targeting a drive root, filesystem root, or home
# path is blocked whether or not -Force is present -- -Recurse alone deletes the tree
# (PowerShell only prompts for read-only children, which an agent's session auto-answers),
# so requiring -Force was a bypass. A relative target (./build, node_modules) stays allowed,
# exactly as `rm -rf ./build` does. Without the raw command (an older vendored adapter) this
# branch is skipped and the bash `rm` path above still applies.
raw="${CHOCK_RAW_COMMAND-}"
if [ -n "$raw" ]; then
    shopt -s nocasematch 2>/dev/null || true
    verb_re='(^|[|;&[:space:]])(remove-item|ri|rd|rmdir|del|erase)([[:space:]]|$)'
    recurse_re='(-recurse|-r([[:space:]]|$)|/s([[:space:]]|$))'
    target_re='([a-z]:[\\/]|[a-z]:([[:space:]]|$)|(^|[[:space:]])[\\/]([[:space:]]|$)|~|\$home|\$env:userprofile|\$env:home)'
    if [[ "$raw" =~ $verb_re ]] && [[ "$raw" =~ $recurse_re ]] && [[ "$raw" =~ $target_re ]]; then
        echo "BLOCKED: destructive PowerShell/cmd removal targeting a drive root or home path is not allowed without approval." >&2
        exit 1
    fi
    shopt -u nocasematch 2>/dev/null || true
fi

exit 0
