#!/usr/bin/env bash
# Generated by Chock. Blocks git commit/push --no-verify or -n flag tokens.
# Best-effort guard; bypasses are possible via aliases, subshells, or non-standard clients.
set -eu

# The real git subcommand is the first NON-OPTION token after git's global options --
# not merely the first `commit`/`push` token anywhere. A `commit` or `push` that appears
# after the real subcommand is an operand (a ref, a pathspec after `--`), so
# `git status -- commit` is `status`, not `commit`, and must not be treated as one.
# Global options either consume the next token as a value (-c, -C, --git-dir, --work-tree,
# --namespace, --exec-path, --super-prefix, --config-env in their spaced form) or stand
# alone; the `=`-attached spellings carry their own value.
_git_subcommand() {
    local expect_value=0 tok
    for tok in "$@"; do
        if [[ "$expect_value" -eq 1 ]]; then
            expect_value=0
            continue
        fi
        case "$tok" in
            git | */git) continue ;;
            -c | -C | --git-dir | --work-tree | --namespace | --exec-path | --super-prefix | --config-env)
                expect_value=1
                continue
                ;;
            --*=*) continue ;;
            -*) continue ;;
            *)
                printf '%s' "$tok"
                return 0
                ;;
        esac
    done
    return 0
}

subcommand="$(_git_subcommand "$@")"
case "$subcommand" in
    commit) has_commit=1 ;;
    push) has_commit=0 ;;
    *) exit 0 ;;
esac

# `git -c core.hooksPath=<somewhere-empty> commit` disables every hook without ever typing
# --no-verify. Same intent, same outcome, and it was completely uncovered: a policy that
# blocks the flag while allowing the config override blocks the spelling, not the behaviour.
#
# Matched only as the VALUE FOLLOWING `-c`, never as free text. Scanning every argument
# blocked `git commit -m "core.hooksPath=... is a bypass"` -- a message that merely mentions
# the setting changes no configuration, and a guard that refuses people for describing the
# thing it guards against trains them to work around it.
# Compared lowercased: git config keys are case-insensitive, so -c CORE.HOOKSPATH=...
# bypasses hooks exactly as the canonical spelling does (verified against git directly).
# The bare valueless form `-c core.hooksPath` is deliberately NOT matched: git rejects it
# with rc=128 before any hook or commit runs, so there is nothing to block.
prev=""
for arg in "$@"; do
    if [[ "$prev" == "-c" && "${arg,,}" == core.hookspath=* ]]; then
        echo "BLOCKED: git $subcommand with -c core.hooksPath disables every hook, exactly as --no-verify does. Fix the failing hook instead of routing around it." >&2
        exit 1
    fi
    prev="$arg"
done

# Short `-n` means --no-verify only on `git commit`. On `git push`, -n is --dry-run --
# non-mutating and NOT a hook bypass (pre-push still runs on a dry-run) -- so blocking
# it there refused a harmless command while teaching nothing (found in external
# review). --no-verify is blocked on both: push has the long flag with the same
# hook-skipping meaning.
has_n=0
for arg in "$@"; do
    # git accepts any unambiguous prefix, so `--no-veri`, `--no-verif` and `--no-verify`
    # all skip hooks. The floor is `--no-veri` (9 chars): `--no-ver` and shorter collide
    # with `--no-verbose`, which git rejects as ambiguous, so there is nothing to block
    # there. Matched as "arg is a prefix of --no-verify, at least 9 chars long".
    if [[ ${#arg} -ge 9 && "--no-verify" == "$arg"* ]]; then
        has_n=1
    elif [[ "$has_commit" -eq 1 && "$arg" == "-n" ]]; then
        has_n=1
    elif [[ "$has_commit" -eq 1 && "$arg" =~ ^-[^-] ]]; then
        # Combined short flags: block if the token contains 'n' (e.g. -nm) -- unless
        # the cluster starts with a value-taking option (-m/-F), where the rest of
        # the token is that option's VALUE: `-mnote` is a message, not flags, and
        # nothing after the value can be an option.
        if [[ "$arg" != -m* && "$arg" != -F* && "$arg" == *n* ]]; then
            has_n=1
        fi
    fi
done

if [[ "$has_n" -eq 1 ]]; then
    echo "BLOCKED: git $subcommand --no-verify is not allowed. Fix the hook failure instead." >&2
    exit 1
fi

exit 0
