#!/usr/bin/env bash
# Generated by Chock. Best-effort guard against piping a network download into a shell.
# Not a security boundary; bypasses via aliases, indirection, or obfuscation are possible.
set -eu

# The threat: `curl https://x | sh` (and its kin) runs code fetched from the network with no
# chance to read it first -- the canonical malicious-installer and agent-supply-chain vector.
# We block ONLY when a network FETCH is wired DIRECTLY into a shell interpreter. Downloading
# to a file, or piping a fetch into a non-shell (jq, grep, tar), stays allowed -- that is the
# safe form the block message points people toward.
#
# Pipes, process substitution and command substitution are shell SYNTAX, lost once the adapter
# tokenizes argv, so we match the raw command text the adapter preserves in CHOCK_RAW_COMMAND.
# Without it (an older vendored adapter) we reconstruct a best-effort string from argv so the
# common `curl ... | sh` still trips.
raw="${CHOCK_RAW_COMMAND-}"
if [ -z "$raw" ]; then
    raw="$*"
fi
[ -z "$raw" ] && exit 0

# A command whose whole job is to PRINT the pattern (documentation, an echo, a comment) is not
# executing it. Skip when the first word is a printer/comment so `echo "curl x | sh"` and
# `# curl x | sh` stay allowed -- the same echo-prefix false-positive the other guards carry.
# BUT only for a single simple command: a compound like `echo "installing" && curl x | sh`
# must not be exempted by its harmless first word, so the shortcut is withheld whenever a
# command separator (;, &&, ||) is present and the real command is inspected below.
case "$raw" in
    *';'* | *'&&'* | *'||'*) : ;; # compound: fall through to the fetch/pipe check
    *)
        first="$(printf '%s' "$raw" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]].*//')"
        case "$first" in
            echo | printf | print | : | \#*) exit 0 ;;
        esac
        ;;
esac

shopt -s nocasematch 2>/dev/null || true

# A network fetcher anywhere in the command. Named tools only -- a bare URL is not enough,
# because it is the FETCH-into-shell wiring, not the presence of a link, that is dangerous.
fetch_re='(^|[[:space:];|&(<.])(curl|wget|lynx|fetch|aria2c|iwr|invoke-webrequest|invoke-restmethod|irm|start-bitstransfer|net\.webclient|downloadstring|downloaddata|downloadfile)([[:space:](./)]|$)'

# A shell or script interpreter fed by a pipe. Covers, in one matcher: a bare or path-qualified
# interpreter (`| sh`, `| /bin/sh`), a no-space pipe (`...|sh`), grouped consumers that still
# receive the fetch on stdin (`| (sh)`, `| { sh; }`), and transparent wrappers in front of it
# (`| sudo bash`, `| exec sh`, `| command sh`, `| env python`). python/perl/ruby/node are
# included because piping a download into them executes the fetched code exactly as a shell does.
pipe_re='\|&?[[:space:]]*[({]?[[:space:]]*((sudo|exec|command|env)[[:space:]]+(-[^[:space:]|;&(){}]+[[:space:]]+)*)*([^[:space:]|;&(){}]*/)?(sh|bash|zsh|dash|ksh|ash|fish|python[0-9.]*|perl|ruby|node)([[:space:]);}]|$)'
# A shell interpreter fed by process/command substitution: `bash -c "$(...)"`, `sh <(...)`.
subst_re='(sh|bash|zsh|dash|ksh|python[0-9.]*|perl|ruby|node)[[:space:]]+(-[[:alnum:]]+[[:space:]]+)*["'"'"']?(\$\(|<\()'
# PowerShell: `... | iex`, `iex(...)`, `Invoke-Expression(...)`.
iex_re='(\|[[:space:]]*(iex|invoke-expression)([[:space:]]|$)|(iex|invoke-expression)[[:space:]]*\()'

if [[ "$raw" =~ $fetch_re ]]; then
    if [[ "$raw" =~ $pipe_re ]] || [[ "$raw" =~ $subst_re ]] || [[ "$raw" =~ $iex_re ]]; then
        echo "BLOCKED: piping a network download into a shell (curl|wget|iwr ... | sh/bash/iex) runs unreviewed remote code. Download to a file, read it, then run it." >&2
        exit 1
    fi
fi

shopt -u nocasematch 2>/dev/null || true
exit 0
