"""Build the scenarios a rule is measured on — generated by a model, or supplied by hand."""

from __future__ import annotations

import json
import re
from pathlib import Path

from context_report.efficacy import prompts
from context_report.efficacy.backends import Asker
from context_report.efficacy.core import RuleCard, Scenario
from context_report.efficacy.rules import Rule

DEFAULT_COUNT = 4

_JSON_ARRAY = re.compile(r"\[.*\]", re.DOTALL)
_NO_ARRAY = "no JSON array of tasks in the model's reply: {reply!r}"
_EMPTY = (
    "no scenarios for rule {rule_id!r} — supply them with --scenarios or raise --scenarios-per-rule"
)


def parse_tasks(reply: str) -> list[str]:
    """Read the task list out of a model reply that should be a JSON array of strings."""
    match = _JSON_ARRAY.search(reply)
    if match is None:
        raise ValueError(_NO_ARRAY.format(reply=reply[:200]))
    parsed = json.loads(match.group(0))
    return [str(task).strip() for task in parsed if str(task).strip()]


def generate(rule: Rule, asker: Asker, count: int = DEFAULT_COUNT) -> list[str]:
    """Ask the model for tasks where the rule applies but is never mentioned."""
    reply = asker.ask(prompts.render("scenarios", rule=rule.text, count=str(count)))
    return parse_tasks(reply)[:count]


def load(path: str | Path) -> dict[str, list[str]]:
    """Hand-written scenarios: a JSON object of rule id -> list of task prompts."""
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return {str(rule_id): [str(t) for t in tasks] for rule_id, tasks in data.items()}


def card(rule: Rule, tasks: list[str]) -> RuleCard:
    """Pair a rule with its scenarios in the shape the engine measures."""
    if not tasks:
        raise ValueError(_EMPTY.format(rule_id=rule.id))
    scenarios = tuple(
        Scenario(id=f"{rule.id}#{index}", task=task, rule_applies=rule.text)
        for index, task in enumerate(tasks)
    )
    return RuleCard(id=rule.id, text=rule.text, scenarios=scenarios)
