#!/usr/bin/env bash
# Generated by Chock. Refuses shell commands that write to CI/CD workflow config -- an
# agent must not weaken the automated checks that review its own work. Reads pass;
# `chock sync` and other tool-driven writes pass. Best-effort and coarse by design: when
# in doubt it blocks, and the fix is a two-step command or a human-approved run carrying
# 'chock: approved-config-change'.
set -eu

# Include the raw command string: Windows path forms and `bash -c "..."` payloads arrive
# here as one argument, and CHOCK_RAW_COMMAND carries the pre-split original.
full="$* ${CHOCK_RAW_COMMAND:-}"
# Normalize backslashes so a Windows `.github\workflows\ci.yml` matches the POSIX form.
norm="${full//\\//}"

# A human-approved change says so in the command itself, visibly.
case "$full" in
    *"chock: approved-config-change"*) exit 0 ;;
esac

# Whole-token raw writers (deleters/movers/editors). Word-split with globbing disabled so a
# `bash -c "rm ..."` payload is reached, and basename-normalized so /bin/rm and a bare rm
# both match.
_has_writer_token() {
    local tok
    set -f
    for tok in $1; do
        case "${tok##*/}" in
            tee | rm | mv | cp | chmod | truncate | patch | dd | ed | ex) set +f; return 0 ;;
        esac
    done
    set +f
    return 1
}
# Interpreters invoked in a *writing* form: a code/in-place flag AFTER an interpreter token
# within the same command string, so option order does not matter and a path-qualified
# interpreter still matches, yet a `bash -c` wrapper's own -c is not misattributed.
_interp_write() {
    local seen=0 tok
    set -f
    for tok in $1; do
        case "${tok##*/}" in
            python | python3 | perl | ruby | node) seen=1 ;;
        esac
        case "$tok" in
            -c | -e | --eval | -i | --in-place | -i.* | -pi | -pi.* | -ni | -ne)
                if [ "$seen" -eq 1 ]; then set +f; return 0; fi ;;
        esac
    done
    set +f
    return 1
}

# git subcommands that overwrite a tracked file from another ref or the index -- a write to
# the protected path even though no rm/cp/redirect token appears. `git checkout <ref> -- path`,
# `git checkout path`, and `git restore path` all replace the worktree file (e.g. reverting a
# workflow to a weaker earlier version). Only trips when BOTH git and a mutating subcommand are
# present; `git checkout <branch>`, `git status`, `git log` carry no protected path and pass the
# protected-path gate below regardless.
_git_worktree_write() {
    local has_git=0 has_mut=0 tok
    set -f
    for tok in $1; do
        case "${tok##*/}" in
            git) has_git=1 ;;
        esac
        case "$tok" in
            checkout | restore) has_mut=1 ;;
        esac
    done
    set +f
    [ "$has_git" -eq 1 ] && [ "$has_mut" -eq 1 ]
}

has_writer=0
# In-place editors and shell redirection (substring: reaches bash -c payloads).
case "$full" in
    *"sed -i"* | *"--in-place"* | *">"*) has_writer=1 ;;
esac
# argv and raw command are each word-split and scanned separately (never concatenated).
if _has_writer_token "$*" || _has_writer_token "${CHOCK_RAW_COMMAND:-}"; then
    has_writer=1
fi
if _interp_write "$*" || _interp_write "${CHOCK_RAW_COMMAND:-}"; then
    has_writer=1
fi
if _git_worktree_write "$*" || _git_worktree_write "${CHOCK_RAW_COMMAND:-}"; then
    has_writer=1
fi
if [[ "$has_writer" -eq 0 ]]; then
    exit 0
fi

# Protected CI/CD paths, matched against the backslash-normalized command line. These are the
# files that define the automated checks on a change: workflow definitions, the composite
# actions they call, and the dependency-update automation.
protected=""
case "$norm" in
    *.github/workflows/* | \
    *.github/actions/* | \
    *.github/dependabot.yml* | *.github/dependabot.yaml*)
        protected=yes
        ;;
esac

if [[ -n "$protected" ]]; then
    echo "BLOCKED: shell write touching CI/CD workflow config is not allowed -- an agent must not weaken the automated checks that review its own work. Propose the change for human review, or approve by including 'chock: approved-config-change' in the command." >&2
    exit 1
fi

exit 0
